"""delete specifier column

Revision ID: 9f3355882c67
Revises: dd222d206340
Create Date: 2024-07-14 09:54:22.623452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3355882c67'
down_revision: Union[str, None] = 'dd222d206340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examination_score', 'subject_specifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination_score', sa.Column('subject_specifier', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
