"""edit_stamp correctn name

Revision ID: d5774f50349f
Revises: b23d87c6f6eb
Create Date: 2024-12-21 16:46:08.769572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5774f50349f'
down_revision: Union[str, None] = 'b23d87c6f6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('edit_stamp', sa.String(length=60), nullable=True))
    op.drop_column('examination', 'edit_stmap')
    op.add_column('examination_score', sa.Column('edit_stamp', sa.String(length=60), nullable=True))
    op.drop_column('examination_score', 'edit_stmap')
    op.add_column('municipality', sa.Column('edit_stamp', sa.String(length=60), nullable=True))
    op.drop_column('municipality', 'edit_stmap')
    op.add_column('place', sa.Column('edit_stamp', sa.String(length=60), nullable=True))
    op.drop_column('place', 'edit_stmap')
    op.add_column('region', sa.Column('edit_stamp', sa.String(length=60), nullable=True))
    op.drop_column('region', 'edit_stmap')
    op.add_column('school', sa.Column('edit_stamp', sa.String(length=60), nullable=True))
    op.drop_column('school', 'edit_stmap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('edit_stmap', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('school', 'edit_stamp')
    op.add_column('region', sa.Column('edit_stmap', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('region', 'edit_stamp')
    op.add_column('place', sa.Column('edit_stmap', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('place', 'edit_stamp')
    op.add_column('municipality', sa.Column('edit_stmap', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('municipality', 'edit_stamp')
    op.add_column('examination_score', sa.Column('edit_stmap', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('examination_score', 'edit_stamp')
    op.add_column('examination', sa.Column('edit_stmap', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('examination', 'edit_stamp')
    # ### end Alembic commands ###
