"""move examination_score

Revision ID: 4e56f55f89cd
Revises: d5774f50349f
Create Date: 2024-12-23 15:14:11.849156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e56f55f89cd'
down_revision: Union[str, None] = 'd5774f50349f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('max_possible_score', sa.Numeric(), nullable=True))
    op.drop_column('examination_score', 'max_possible_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination_score', sa.Column('max_possible_score', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('examination', 'max_possible_score')
    # ### end Alembic commands ###
