"""add wikidata columns

Revision ID: d7abcecaa8ee
Revises: 9f3355882c67
Create Date: 2024-11-24 17:03:17.831014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7abcecaa8ee'
down_revision: Union[str, None] = '9f3355882c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipality', sa.Column('region_wd', sa.String(length=100), nullable=True))
    op.add_column('municipality', sa.Column('wd', sa.String(length=100), nullable=True))
    op.add_column('place', sa.Column('municipality_wd', sa.String(length=100), nullable=True))
    op.add_column('place', sa.Column('wd', sa.String(length=100), nullable=True))
    op.add_column('place', sa.Column('type', sa.String(length=4), nullable=True))
    op.add_column('place', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('place', sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True))
    op.add_column('region', sa.Column('wd', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'wd')
    op.drop_column('place', 'latitude')
    op.drop_column('place', 'longitude')
    op.drop_column('place', 'type')
    op.drop_column('place', 'wd')
    op.drop_column('place', 'municipality_wd')
    op.drop_column('municipality', 'wd')
    op.drop_column('municipality', 'region_wd')
    # ### end Alembic commands ###
