"""school wikidata_id

Revision ID: 8bdca47ef321
Revises: 5b68c8828799
Create Date: 2024-12-05 22:47:02.151539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdca47ef321'
down_revision: Union[str, None] = '5b68c8828799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('wikidata_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'wikidata_id')
    # ### end Alembic commands ###
