"""add_school_funding_source

Revision ID: 695adfe1596d
Revises: c4fb9d774a75
Create Date: 2025-02-23 13:21:08.531108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695adfe1596d'
down_revision: Union[str, None] = 'c4fb9d774a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_funding_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funding_type', sa.String(length=10), nullable=False),
    sa.Column('funding_institution_name', sa.String(length=60), nullable=True),
    sa.Column('edit_stamp', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(
        "insert into school_funding_source values(1, '-', '-', 'migration_2025_02_23')"
    )

    # Reset the sequence to start after our inserted record
    op.execute(
        "SELECT setval(pg_get_serial_sequence('school_funding_source', 'id'), (SELECT MAX(id) FROM school_funding_source))"
    )

    op.add_column('school', sa.Column('school_funding_source_id', sa.Integer(), nullable=True))

    op.execute(
        'UPDATE school SET school_funding_source_id = 1 WHERE school_funding_source_id IS NULL'
    )

    op.alter_column('school', 'school_funding_source_id',
        existing_type=sa.Integer(),
        nullable=False
    )

    op.create_foreign_key(None, 'school', 'school_funding_source', ['school_funding_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school', type_='foreignkey')
    op.drop_column('school', 'school_funding_source_id')
    op.drop_table('school_funding_source')
    # ### end Alembic commands ###
